env                 = "dev"
location            = "eastus"
address_space       = "10.10.0.0/16"
subnet_prefix       = "10.10.1.0/24"
vm_size             = "Standard_B2s"
admin_username      = "azureuser"
ssh_public_key_path = "/Users/alexander/.ssh/id_rsa.pub"
allowed_ssh_cidr    = "73.112.170.171/32"
